### ISSUE TITLE
Blank White Screen on 13.1-RELEASE

### ISSUE THREAD

**Issue by jasker5183** [AfroUSApl/iocage-plugin-piwigo#6]
Trying to get this plugin going on Truenas 13-U1 [here](https://github.com/ix-plugin-hub/iocage-plugin-index/pull/322) but the plugin loads to a white screen on the admin portal without any indication in the logs of what the problem is.

**Comment by AfroUSApl** [comment]
This should be fixed with last update, please check.

**Comment by jasker5183** [comment]
It installs successfully now and you can get to the admin portal. But once you add your users and choose your passwords on the installation page then click the "begin installation" button it goes to a blank white screen and stays there. Still not working.

**Comment by AfroUSApl** [comment]
I think it's still waiting for approving review by at least one reviewer with write access on GitHub to pass with update. As it's still pulling old version with release 13 and PHP8

Try to install piwigo from the internet manually:

`iocage fetch -P piwigo -g https://github.com/AfroUSApl/iocage-plugin-piwigo ip4_addr="interface|IPaddress"`

where _interface_ is the name of the active network interface and _IP address_ is the desired IP address for the plugin. For example, ip4_addr="igb0|192.168.0.91"

**Comment by jasker5183** [comment]
My fault for not following the post install notes. I went to your PR and grabbed/fetched the piwigo.json from there and tried an install, following the post install instructions this time still resulted in a blank white screen. When I clicked back it told me that Piwigo was already installed and this time when going to the admin portal I was greeted with the administration page. It does in fact work.

I then went and re-tried the normal install that uses php80 (from the TrueNAS GUI) and it works as well. I don't know what good the PR does other than updating the icon file? It looks like (https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=261604) php74 is going eol here at the end of the month, and if Piwigo works with php80 I would just drop that PR and refile one for an icon change.
